### ISSUE TITLE
Ryzen Master 1.5.4.1334

### ISSUE THREAD

**Issue by intel352** [klauspost/ryzen-master-vbs-patch#1]
I've downloaded Ryzen Master directly from AMD for the 2950x. Installer says version 2.2.0.1543, digital signature 5/7.
The actual bin version that gets installed is 1.5.4.1334, modified 9/23/2019.

Patcher is failing to patch this, I assume because the Ryzen Master installer is delivering an older release for me?

**Comment by klauspost** [comment]
Sounds likely. What does the About page list as the version?

**Comment by intel352** [comment]
Had to manually hex edit, now that I'm in, says 2.2.0.1543

**Comment by klauspost** [comment]
@intel352 What was the before/after sequence?

If you give a some bytes before around the change I can add another check [similar to the existing](https://github.com/klauspost/ryzen-master-vbs-patch/blob/master/main.go#L39).

**Comment by klauspost** [comment]
I verified the patch still works on "v2.2.0.1543" for non-threadripper.

**Comment by neoKushan** [comment]
@klauspost I made the edit myself and took this screenshot for you (Original on the left, modified on the right):

![Threadripper](https://user-images.githubusercontent.com/1029699/83351641-b8623d80-a33d-11ea-811b-3d74937c4313.png)

0x000125E0 original:
`90 E8 5A D7 01 00 39 7D 90 0F 84 E8 00 00 00 33`

0x000125E0 Patched:
`90 E8 5A D7 01 00 39 7D 90 90 E9 E8 00 00 00 33`

**Comment by klauspost** [comment]
@neoKushan Nice. I've added a slightly shorter version of the patch to #2 

Is it possible for you to test this: [ryzen-master-vbs-patch-v1.1.0.zip](https://github.com/klauspost/ryzen-master-vbs-patch/files/4707621/ryzen-master-vbs-patch-v1.1.0.zip)

**Comment by neoKushan** [comment]
Yup, that seems to work!

![image](https://user-images.githubusercontent.com/1029699/83352441-45f45c00-a343-11ea-94f3-d32090dabfaa.png)

I compared the output .exe with the one I've patched myself and can confirm it's identical:

![image](https://user-images.githubusercontent.com/1029699/83352454-5c9ab300-a343-11ea-9f35-f1ef7a5f5a71.png)

And if there was any doubt:

![image](https://user-images.githubusercontent.com/1029699/83352474-881d9d80-a343-11ea-9f20-166c81332991.png)

Thanks, Klaus!

**Comment by klauspost** [comment]
Cool - thanks for the patch and for testing. Merging it now.
