### ISSUE TITLE
Not working with version 2.6.2.1818

### ISSUE THREAD

**Issue by LonerDan** [klauspost/ryzen-master-vbs-patch#12]
Hi, 
I have tested this on the latest version and it doesn't work.
![image](https://user-images.githubusercontent.com/11718484/116722366-9609f180-a9de-11eb-9358-0dace8c95813.png)
![image](https://user-images.githubusercontent.com/11718484/116722323-88546c00-a9de-11eb-912c-e1793f463e8f.png)

**Comment by klauspost** [comment]
@LonerDan I didn't need it for this update. Kind of suspecting AMD actually fixed this.

Have you tried running without the patch?

**Comment by LonerDan** [comment]
Yes, I have. Still gives me the VBS error.

**Comment by klauspost** [comment]
@LonerDan OK. It might be an updated HyperV on my system that can pass through the flags correctly. I will see if I can locate the patch location.

**Comment by LonerDan** [comment]
That's weird.  I have installed all updates and hyper-v should be updated with OS.
OS: Windows 10 Education 20H2 build 19042.928

**Comment by klauspost** [comment]
@LonerDan I found the patch point in 2.6.2.1818 (the one that installed on my 3950x at least). Could you check if this fixes it for you, then I will release it:

https://github.com/klauspost/ryzen-master-vbs-patch/pull/13

Binary: [ryzen-master-vbs-patch-v1.4.0.zip](https://github.com/klauspost/ryzen-master-vbs-patch/files/6414054/ryzen-master-vbs-patch-v1.4.0.zip)

**Comment by LonerDan** [comment]
Thank you, I can confirm it is working now 👍
