### ISSUE TITLE
Ryzen 2.8.0.1937 confirmed

### ISSUE THREAD

**Issue by PeopleDispose** [klauspost/ryzen-master-vbs-patch#16]
Not really an issue but I was too lazy to create a PR for README ;)
I have 2.8.0.1937 Ryzen Master installed and I confirm that your patch successfully skips VBS check during software startup.

**Comment by klauspost** [comment]
Thanks for the information!

Readme updated!

**Comment by roughnecks** [comment]
I just downloaded 2.8.0.1937 from GURU3D and after patching and running it my Windows got a BSOD.
I have latest and greatest Win 10 updates and I'm running a VM on Hyper-V.

I didn't have my phone around so I couldn't get the error code but it had to do with ryzenmasterdriver.sys
