### ISSUE TITLE
Not working on Windows Sever 2022 (21H2) and 2.6.2.1818 or 2.8.0.1937

### ISSUE THREAD

**Issue by kpdozer** [klauspost/ryzen-master-vbs-patch#17]
Hello. I get success message but version check is not disabled.

* Host CPU: AMD Ryzen 9 3950X 16-Core Processor

Reading "AMD Ryzen Master.exe"

0. Checking patch for "Ryzen Master v.1.5 -> v2.2". Matching byte sequences: 0 (should be 1)
1. Checking patch for "Ryzen Master v2.3 -> 2.4.x". Matching byte sequences: 0 (should be 1)
2. Checking patch for "Ryzen Master v2.6 -> ?". Matching byte sequences: 1 (should be 1)
Success! Writing to "patched-AMD Ryzen Master.exe"
![Снимок](https://user-images.githubusercontent.com/88844867/147594610-43acb9c7-2d8b-46be-ad41-b2b45f37aacb.PNG)

**Comment by kpdozer** [comment]
I'm sorry, I figured out what this patch does. Is it possible to disable checking the OS version?

**Comment by klauspost** [comment]
> I'm sorry, I figured out what this patch does. Is it possible to disable checking the OS version?

No. Sorry.
