### ISSUE TITLE
VBS Patch Not Working for Ryzen Master v2.8.1937

### ISSUE THREAD

**Issue by neurolag** [klauspost/ryzen-master-vbs-patch#18]
Hi @klauspost - thanks for your great effort!

Despite the description in your README, I couldn't manage it to get Ryzen Master to work on my machine using the patch.
After applying it, I got the following error message:

![image](https://user-images.githubusercontent.com/7085564/205778934-84ecc63a-bf54-478f-be0d-e93497a5366b.png)

> Ryzen Master unable to initialize. Kindly reinstall the program.

After receiving this, I tried to replace the branch which leads to this error message:
![image](https://user-images.githubusercontent.com/7085564/205779362-7cce602d-b65c-4862-b8b2-db3000da7184.png)

I tried to replace the operation `jz      loc_1400133E0` located at (`0x126F2`) with the op-codes of `nop` and `jump` (`0x90`, `0xE9`).

After doing so, Ryzen Master won't even start and, instead, close immediately with Exit Code `-1073741819`.
Is there a chance that you have an advice for me?

**Comment by klauspost** [comment]
@manuth You may be looking for the solution to another problem. Recent versions have not needed patching, so it is likely it cannot be initialized for another reason.

I suggest you contact AMD with your problem.
