### ISSUE TITLE
Ryzen Master 2.3.0.1591 - no byte sequence not found

### ISSUE THREAD

**Issue by zi0Black** [klauspost/ryzen-master-vbs-patch#4]
I made fresh installation of AMD ryzen from there:
https://www.amd.com/en/technologies/ryzen-master (2.3.0.1591)

After I tried to run the tool but looks like there is some kind of problem with matching a sequence of bytes.

```powershell
PS C:\Program Files\AMD\RyzenMaster\bin> ./ryzen-master-vbs-patch.exe -p "patched" ./"AMD Ryzen Master.exe"
Reading "AMD Ryzen Master.exe"
0. Checking patch for "Ryzen Master v.1.5 -> v2.2". Matching byte sequences: 0 (should be 1)
1. Checking patch for "Ryzen Master v2.3 -> ?". Matching byte sequences: 0 (should be 1)
2. Checking patch for "Ryzen Master Threadripper". Matching byte sequences: 0 (should be 1)
no byte sequence not found
PS C:\Program Files\AMD\RyzenMaster\bin> ./ryzen-master-vbs-patch.exe -p "patched" "AMD Ryzen Master.exe"
Reading "AMD Ryzen Master.exe"
0. Checking patch for "Ryzen Master v.1.5 -> v2.2". Matching byte sequences: 0 (should be 1)
1. Checking patch for "Ryzen Master v2.3 -> ?". Matching byte sequences: 0 (should be 1)
2. Checking patch for "Ryzen Master Threadripper". Matching byte sequences: 0 (should be 1)
no byte sequence not found
PS C:\Program Files\AMD\RyzenMaster\bin>
```

**Comment by LoLo2207** [comment]
So I just discovered this tool and tried it. I too made a fresh install of Ryzen Master 2.3.0.1591

In my case, with a Ryzen 7 2700, the output is 

```
C:\Users\LoLo\Desktop>ryzen-master-vbs-patch.exe
Reading "AMD Ryzen Master.exe"
0. Checking patch for "Ryzen Master v.1.5 -> v2.2". Matching byte sequences: 0 (should be 1)
1. Checking patch for "Ryzen Master v2.3 -> ?". Matching byte sequences: 0 (should be 1)
2. Checking patch for "Ryzen Master Threadripper". Matching byte sequences: 1 (should be 1)
Writing to "patched-AMD Ryzen Master.exe"
```
which I don't now if it's weird or not (Threadripper), but after copying back the patched .exe, it worked

![imagen](https://user-images.githubusercontent.com/9082819/91087082-3178e480-e650-11ea-95d2-551c2f9f9d2c.png)

**Comment by klauspost** [comment]
> 2. Checking patch for "Ryzen Master Threadripper". Matching byte sequences: 1 (should be 1)
> Writing to "patched-AMD Ryzen Master.exe"

@LoLo2207  This indicates it was patched correctly. It tries different patches for different versions.

**Comment by klauspost** [comment]
@zi0Black What is your system' CPU?

AMD has a nasty habit of installing different versions for different CPUs.

**Comment by zi0Black** [comment]
Ryzen 7 1800x

**Comment by KaelanParsons** [comment]
On my system (R7 1700x), I can patch out the check by replacing: 
{0x72, 0x62, 0x01, 0x00, 0x39, 0x74, 0x24, 0x68, 0x0f, 0x84} -> {0x72, 0x62, 0x01, 0x00, 0x39, 0x74, 0x24, 0x68, 0x90, 0xe9}


![image](https://user-images.githubusercontent.com/462101/91117958-40ed4180-e6d3-11ea-8cde-ac1dbfe9e175.png)

**Comment by AgentAngelic** [comment]
I just discovered this as well. I have a Ryzen 6 1600X
```
C:\Users\deven\Downloads\patch>ryzen-master-vbs-patch -p "patched" "AMD Ryzen Master.exe"
Reading "AMD Ryzen Master.exe"
0. Checking patch for "Ryzen Master v.1.5 -> v2.2". Matching byte sequences: 0 (should be 1)
1. Checking patch for "Ryzen Master v2.3 -> ?". Matching byte sequences: 0 (should be 1)
2. Checking patch for "Ryzen Master Threadripper". Matching byte sequences: 0 (should be 1)
no byte sequence not found
```

**Comment by klauspost** [comment]
@kaelanduck Thanks! Added your patch 👍   @zi0Black @AgentAngelic I have added a new release.
