### ISSUE TITLE
AMD Ryzen™ Master Monitoring SDK support

### ISSUE THREAD

**Issue by Paranoid-Dev** [klauspost/ryzen-master-vbs-patch#5]
As the title says, can you add support to https://developer.amd.com/amd-ryzentm-master-monitoring-sdk/ as well?

**Comment by klauspost** [comment]
`AMDRyzenMasterMonitoringSampleApp.exe` works fine here and it seems like the CPUID detection is in `sampleApp.cpp` anyways. So I am not sure it is necessary.

I tested with `AMD_RM_Monitoring_SDK_2.2.0.1543.exe`.

Either way I don't think that is something I want to commit to.
