### ISSUE TITLE
Virus detected in release 1.3

### ISSUE THREAD

**Issue by shawnrmoss** [klauspost/ryzen-master-vbs-patch#6]
Windows 10 wont allow your release to be downloaded.  
Virus detected
Win32/Wacatac.DE!ml

**Comment by klauspost** [comment]
I will check with virustotal - some bad av has been detecting all Go programs as infected.

**Comment by klauspost** [comment]
I have verified the binary is the same as I uploaded. Scan results:

The EXE: https://www.virustotal.com/gui/file/e2f733b3bcb1c7a9021f70dbd3f337dcf2b50d1569369034cdb3e211e2cb736d/detection

One false positive. The SHA256 matches the executable on my system.

The ZIP: https://www.virustotal.com/gui/file/aafcd06b6d7053ab45b239ebbbca9d0763b7e664245f4463c39416745c6eb7d9/detection

There isn't much I can do against false positives.
