### ISSUE TITLE
Just wanted to say thanks!

### ISSUE THREAD

**Issue by GiorgioG** [klauspost/ryzen-master-vbs-patch#7]
This works great!  Thanks again.  Can't believe AMD won't just do this out of the gate.  It's been years since I have been dealing with this nonsense (1950x running at 4.0ghz.)

Thanks again!

**Comment by klauspost** [comment]
@GiorgioG Thanks! Seems like a stupid thing from AMD indeed <3

**Comment by hjkl950217** [comment]
I am also very grateful! By the way, AMD's inaction

**Comment by AlphaJuliettOmega** [comment]
Get pinged by my thanks!
