### ISSUE TITLE
Please add support for new 2.6.xxx ryzen master version

### ISSUE THREAD

**Issue by martonx** [klauspost/ryzen-master-vbs-patch#9]
Please add support for new 2.6.xxx ryzen master version if the issue is exist with new version.

**Comment by klauspost** [comment]
@martonx Have you tried it?

**Comment by Eagle3386** [comment]
@klauspost I did - version 2.6.0.1692 patched successfully! 🥳🍻
Again, thanks a lot for creating & providing this patch to the community! ❤️

**Comment by klauspost** [comment]
Great. Adding it to the list.

**Comment by FeikoWielsma** [comment]
Hi! I just tried patching v2.6.0.1692; I got it from Guru3D (https://www.guru3d.com/files-get/amd-ryzen-master-utility-download,2.html)
It couldn't find the byte sequence; am I using a wrong Ryzen Master?
![image](https://user-images.githubusercontent.com/8656008/103654083-b90f2200-4f65-11eb-9cdb-b2ec51b9e7b5.png)

**Comment by klauspost** [comment]
@FeikoWielsma Maybe they changed something, but for good measure download it from AMD: https://www.amd.com/en/technologies/ryzen-master

If that doesn't work, zip up the executable and attach it here and I will take a look.

Which CPU are you using?

**Comment by FeikoWielsma** [comment]
I already applied it to the installed version earlier; the one from AMD has the same issue. Attached here is the zip:
[AMD Ryzen Master.zip](https://github.com/klauspost/ryzen-master-vbs-patch/files/5770626/AMD.Ryzen.Master.zip)
I'm using a R5 3600

**Comment by klauspost** [comment]
@FeikoWielsma The file in the zip appears to already be patched. Doesn't it work?

**Comment by FeikoWielsma** [comment]
I'm really confused now: I uninstalled and reinstalled the AMD site version, and I didn't need to patch it at all; it just worked. It definitely didn't do that before, so I guess it's good news?

**Comment by klauspost** [comment]
@FeikoWielsma Maybe some mixup. I wouldn't suspect AMD to release their stuff with the patch applied.

Glad it worked!

**Comment by Eagle3386** [comment]
FYI: After upgrade to RM 2.6.2.1818, `AMD Ryzen Master.exe` needed to be patched again - which worked for my TR 2950X as hoped: just like a charm! 🥳
